/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type AgentRevoked = { authority: Address; agentKey: Address };

export type AgentRevokedArgs = AgentRevoked;

export function getAgentRevokedEncoder(): FixedSizeEncoder<AgentRevokedArgs> {
  return getStructEncoder([
    ["authority", getAddressEncoder()],
    ["agentKey", getAddressEncoder()],
  ]);
}

export function getAgentRevokedDecoder(): FixedSizeDecoder<AgentRevoked> {
  return getStructDecoder([
    ["authority", getAddressDecoder()],
    ["agentKey", getAddressDecoder()],
  ]);
}

export function getAgentRevokedCodec(): FixedSizeCodec<
  AgentRevokedArgs,
  AgentRevoked
> {
  return combineCodec(getAgentRevokedEncoder(), getAgentRevokedDecoder());
}
