/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type AgentRegistered = {
  authority: Address;
  agentKey: Address;
  agentIdentity: Address;
};

export type AgentRegisteredArgs = AgentRegistered;

export function getAgentRegisteredEncoder(): FixedSizeEncoder<AgentRegisteredArgs> {
  return getStructEncoder([
    ["authority", getAddressEncoder()],
    ["agentKey", getAddressEncoder()],
    ["agentIdentity", getAddressEncoder()],
  ]);
}

export function getAgentRegisteredDecoder(): FixedSizeDecoder<AgentRegistered> {
  return getStructDecoder([
    ["authority", getAddressDecoder()],
    ["agentKey", getAddressDecoder()],
    ["agentIdentity", getAddressDecoder()],
  ]);
}

export function getAgentRegisteredCodec(): FixedSizeCodec<
  AgentRegisteredArgs,
  AgentRegistered
> {
  return combineCodec(getAgentRegisteredEncoder(), getAgentRegisteredDecoder());
}
