/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from "@solana/kit";

export type AgreementSigned = {
  agreementId: ReadonlyUint8Array;
  party: Address;
};

export type AgreementSignedArgs = AgreementSigned;

export function getAgreementSignedEncoder(): FixedSizeEncoder<AgreementSignedArgs> {
  return getStructEncoder([
    ["agreementId", fixEncoderSize(getBytesEncoder(), 16)],
    ["party", getAddressEncoder()],
  ]);
}

export function getAgreementSignedDecoder(): FixedSizeDecoder<AgreementSigned> {
  return getStructDecoder([
    ["agreementId", fixDecoderSize(getBytesDecoder(), 16)],
    ["party", getAddressDecoder()],
  ]);
}

export function getAgreementSignedCodec(): FixedSizeCodec<
  AgreementSignedArgs,
  AgreementSigned
> {
  return combineCodec(getAgreementSignedEncoder(), getAgreementSignedDecoder());
}
