/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from "@solana/kit";

export type AgreementFulfilled = { agreementId: ReadonlyUint8Array };

export type AgreementFulfilledArgs = AgreementFulfilled;

export function getAgreementFulfilledEncoder(): FixedSizeEncoder<AgreementFulfilledArgs> {
  return getStructEncoder([
    ["agreementId", fixEncoderSize(getBytesEncoder(), 16)],
  ]);
}

export function getAgreementFulfilledDecoder(): FixedSizeDecoder<AgreementFulfilled> {
  return getStructDecoder([
    ["agreementId", fixDecoderSize(getBytesDecoder(), 16)],
  ]);
}

export function getAgreementFulfilledCodec(): FixedSizeCodec<
  AgreementFulfilledArgs,
  AgreementFulfilled
> {
  return combineCodec(
    getAgreementFulfilledEncoder(),
    getAgreementFulfilledDecoder(),
  );
}
