/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from "@solana/kit";

export type AgreementActivated = { agreementId: ReadonlyUint8Array };

export type AgreementActivatedArgs = AgreementActivated;

export function getAgreementActivatedEncoder(): FixedSizeEncoder<AgreementActivatedArgs> {
  return getStructEncoder([
    ["agreementId", fixEncoderSize(getBytesEncoder(), 16)],
  ]);
}

export function getAgreementActivatedDecoder(): FixedSizeDecoder<AgreementActivated> {
  return getStructDecoder([
    ["agreementId", fixDecoderSize(getBytesDecoder(), 16)],
  ]);
}

export function getAgreementActivatedCodec(): FixedSizeCodec<
  AgreementActivatedArgs,
  AgreementActivated
> {
  return combineCodec(
    getAgreementActivatedEncoder(),
    getAgreementActivatedDecoder(),
  );
}
