/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from "@solana/kit";

export type AgreementProposed = {
  agreementId: ReadonlyUint8Array;
  proposer: Address;
  agreementPda: Address;
};

export type AgreementProposedArgs = AgreementProposed;

export function getAgreementProposedEncoder(): FixedSizeEncoder<AgreementProposedArgs> {
  return getStructEncoder([
    ["agreementId", fixEncoderSize(getBytesEncoder(), 16)],
    ["proposer", getAddressEncoder()],
    ["agreementPda", getAddressEncoder()],
  ]);
}

export function getAgreementProposedDecoder(): FixedSizeDecoder<AgreementProposed> {
  return getStructDecoder([
    ["agreementId", fixDecoderSize(getBytesDecoder(), 16)],
    ["proposer", getAddressDecoder()],
    ["agreementPda", getAddressDecoder()],
  ]);
}

export function getAgreementProposedCodec(): FixedSizeCodec<
  AgreementProposedArgs,
  AgreementProposed
> {
  return combineCodec(
    getAgreementProposedEncoder(),
    getAgreementProposedDecoder(),
  );
}
