/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from "@solana/kit";

export type AgreementCancelled = { agreementId: ReadonlyUint8Array };

export type AgreementCancelledArgs = AgreementCancelled;

export function getAgreementCancelledEncoder(): FixedSizeEncoder<AgreementCancelledArgs> {
  return getStructEncoder([
    ["agreementId", fixEncoderSize(getBytesEncoder(), 16)],
  ]);
}

export function getAgreementCancelledDecoder(): FixedSizeDecoder<AgreementCancelled> {
  return getStructDecoder([
    ["agreementId", fixDecoderSize(getBytesDecoder(), 16)],
  ]);
}

export function getAgreementCancelledCodec(): FixedSizeCodec<
  AgreementCancelledArgs,
  AgreementCancelled
> {
  return combineCodec(
    getAgreementCancelledEncoder(),
    getAgreementCancelledDecoder(),
  );
}
