/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getBooleanDecoder,
  getBooleanEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type DelegationScope = {
  canSignAgreements: boolean;
  canCommitFunds: boolean;
  maxCommitLamports: bigint;
  expiresAt: bigint;
};

export type DelegationScopeArgs = {
  canSignAgreements: boolean;
  canCommitFunds: boolean;
  maxCommitLamports: number | bigint;
  expiresAt: number | bigint;
};

export function getDelegationScopeEncoder(): FixedSizeEncoder<DelegationScopeArgs> {
  return getStructEncoder([
    ["canSignAgreements", getBooleanEncoder()],
    ["canCommitFunds", getBooleanEncoder()],
    ["maxCommitLamports", getU64Encoder()],
    ["expiresAt", getI64Encoder()],
  ]);
}

export function getDelegationScopeDecoder(): FixedSizeDecoder<DelegationScope> {
  return getStructDecoder([
    ["canSignAgreements", getBooleanDecoder()],
    ["canCommitFunds", getBooleanDecoder()],
    ["maxCommitLamports", getU64Decoder()],
    ["expiresAt", getI64Decoder()],
  ]);
}

export function getDelegationScopeCodec(): FixedSizeCodec<
  DelegationScopeArgs,
  DelegationScope
> {
  return combineCodec(getDelegationScopeEncoder(), getDelegationScopeDecoder());
}
