/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type DelegationUpdated = { authority: Address; agentIdentity: Address };

export type DelegationUpdatedArgs = DelegationUpdated;

export function getDelegationUpdatedEncoder(): FixedSizeEncoder<DelegationUpdatedArgs> {
  return getStructEncoder([
    ["authority", getAddressEncoder()],
    ["agentIdentity", getAddressEncoder()],
  ]);
}

export function getDelegationUpdatedDecoder(): FixedSizeDecoder<DelegationUpdated> {
  return getStructDecoder([
    ["authority", getAddressDecoder()],
    ["agentIdentity", getAddressDecoder()],
  ]);
}

export function getDelegationUpdatedCodec(): FixedSizeCodec<
  DelegationUpdatedArgs,
  DelegationUpdated
> {
  return combineCodec(
    getDelegationUpdatedEncoder(),
    getDelegationUpdatedDecoder(),
  );
}
