/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from "@solana/kit";

export type PartyAdded = {
  agreementId: ReadonlyUint8Array;
  party: Address;
  role: number;
};

export type PartyAddedArgs = PartyAdded;

export function getPartyAddedEncoder(): FixedSizeEncoder<PartyAddedArgs> {
  return getStructEncoder([
    ["agreementId", fixEncoderSize(getBytesEncoder(), 16)],
    ["party", getAddressEncoder()],
    ["role", getU8Encoder()],
  ]);
}

export function getPartyAddedDecoder(): FixedSizeDecoder<PartyAdded> {
  return getStructDecoder([
    ["agreementId", fixDecoderSize(getBytesDecoder(), 16)],
    ["party", getAddressDecoder()],
    ["role", getU8Decoder()],
  ]);
}

export function getPartyAddedCodec(): FixedSizeCodec<
  PartyAddedArgs,
  PartyAdded
> {
  return combineCodec(getPartyAddedEncoder(), getPartyAddedDecoder());
}
