/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  expectSome,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const ADD_PARTY_DISCRIMINATOR = new Uint8Array([
  140, 77, 36, 36, 64, 148, 34, 149,
]);

export function getAddPartyDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(ADD_PARTY_DISCRIMINATOR);
}

export type AddPartyInstruction<
  TProgram extends string = typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
  TAccountProposerSigner extends string | AccountMeta<string> = string,
  TAccountProposerIdentity extends string | AccountMeta<string> = string,
  TAccountAgreement extends string | AccountMeta<string> = string,
  TAccountPartyIdentity extends string | AccountMeta<string> = string,
  TAccountParty extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountProposerSigner extends string
        ? WritableSignerAccount<TAccountProposerSigner> &
            AccountSignerMeta<TAccountProposerSigner>
        : TAccountProposerSigner,
      TAccountProposerIdentity extends string
        ? ReadonlyAccount<TAccountProposerIdentity>
        : TAccountProposerIdentity,
      TAccountAgreement extends string
        ? WritableAccount<TAccountAgreement>
        : TAccountAgreement,
      TAccountPartyIdentity extends string
        ? ReadonlyAccount<TAccountPartyIdentity>
        : TAccountPartyIdentity,
      TAccountParty extends string
        ? WritableAccount<TAccountParty>
        : TAccountParty,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type AddPartyInstructionData = {
  discriminator: ReadonlyUint8Array;
  agreementId: ReadonlyUint8Array;
  role: number;
};

export type AddPartyInstructionDataArgs = {
  agreementId: ReadonlyUint8Array;
  role: number;
};

export function getAddPartyInstructionDataEncoder(): FixedSizeEncoder<AddPartyInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["agreementId", fixEncoderSize(getBytesEncoder(), 16)],
      ["role", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: ADD_PARTY_DISCRIMINATOR }),
  );
}

export function getAddPartyInstructionDataDecoder(): FixedSizeDecoder<AddPartyInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["agreementId", fixDecoderSize(getBytesDecoder(), 16)],
    ["role", getU8Decoder()],
  ]);
}

export function getAddPartyInstructionDataCodec(): FixedSizeCodec<
  AddPartyInstructionDataArgs,
  AddPartyInstructionData
> {
  return combineCodec(
    getAddPartyInstructionDataEncoder(),
    getAddPartyInstructionDataDecoder(),
  );
}

export type AddPartyAsyncInput<
  TAccountProposerSigner extends string = string,
  TAccountProposerIdentity extends string = string,
  TAccountAgreement extends string = string,
  TAccountPartyIdentity extends string = string,
  TAccountParty extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  proposerSigner: TransactionSigner<TAccountProposerSigner>;
  proposerIdentity: Address<TAccountProposerIdentity>;
  agreement?: Address<TAccountAgreement>;
  /** The AgentIdentity of the party being added */
  partyIdentity: Address<TAccountPartyIdentity>;
  party?: Address<TAccountParty>;
  systemProgram?: Address<TAccountSystemProgram>;
  agreementId: AddPartyInstructionDataArgs["agreementId"];
  role: AddPartyInstructionDataArgs["role"];
};

export async function getAddPartyInstructionAsync<
  TAccountProposerSigner extends string,
  TAccountProposerIdentity extends string,
  TAccountAgreement extends string,
  TAccountPartyIdentity extends string,
  TAccountParty extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address =
    typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
>(
  input: AddPartyAsyncInput<
    TAccountProposerSigner,
    TAccountProposerIdentity,
    TAccountAgreement,
    TAccountPartyIdentity,
    TAccountParty,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  AddPartyInstruction<
    TProgramAddress,
    TAccountProposerSigner,
    TAccountProposerIdentity,
    TAccountAgreement,
    TAccountPartyIdentity,
    TAccountParty,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    proposerSigner: { value: input.proposerSigner ?? null, isWritable: true },
    proposerIdentity: {
      value: input.proposerIdentity ?? null,
      isWritable: false,
    },
    agreement: { value: input.agreement ?? null, isWritable: true },
    partyIdentity: { value: input.partyIdentity ?? null, isWritable: false },
    party: { value: input.party ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.agreement.value) {
    accounts.agreement.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([97, 103, 114, 101, 101, 109, 101, 110, 116]),
        ),
        fixEncoderSize(getBytesEncoder(), 16).encode(
          expectSome(args.agreementId),
        ),
      ],
    });
  }
  if (!accounts.party.value) {
    accounts.party.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([112, 97, 114, 116, 121])),
        fixEncoderSize(getBytesEncoder(), 16).encode(
          expectSome(args.agreementId),
        ),
        getAddressEncoder().encode(expectAddress(accounts.partyIdentity.value)),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.proposerSigner),
      getAccountMeta(accounts.proposerIdentity),
      getAccountMeta(accounts.agreement),
      getAccountMeta(accounts.partyIdentity),
      getAccountMeta(accounts.party),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getAddPartyInstructionDataEncoder().encode(
      args as AddPartyInstructionDataArgs,
    ),
    programAddress,
  } as AddPartyInstruction<
    TProgramAddress,
    TAccountProposerSigner,
    TAccountProposerIdentity,
    TAccountAgreement,
    TAccountPartyIdentity,
    TAccountParty,
    TAccountSystemProgram
  >);
}

export type AddPartyInput<
  TAccountProposerSigner extends string = string,
  TAccountProposerIdentity extends string = string,
  TAccountAgreement extends string = string,
  TAccountPartyIdentity extends string = string,
  TAccountParty extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  proposerSigner: TransactionSigner<TAccountProposerSigner>;
  proposerIdentity: Address<TAccountProposerIdentity>;
  agreement: Address<TAccountAgreement>;
  /** The AgentIdentity of the party being added */
  partyIdentity: Address<TAccountPartyIdentity>;
  party: Address<TAccountParty>;
  systemProgram?: Address<TAccountSystemProgram>;
  agreementId: AddPartyInstructionDataArgs["agreementId"];
  role: AddPartyInstructionDataArgs["role"];
};

export function getAddPartyInstruction<
  TAccountProposerSigner extends string,
  TAccountProposerIdentity extends string,
  TAccountAgreement extends string,
  TAccountPartyIdentity extends string,
  TAccountParty extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address =
    typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
>(
  input: AddPartyInput<
    TAccountProposerSigner,
    TAccountProposerIdentity,
    TAccountAgreement,
    TAccountPartyIdentity,
    TAccountParty,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): AddPartyInstruction<
  TProgramAddress,
  TAccountProposerSigner,
  TAccountProposerIdentity,
  TAccountAgreement,
  TAccountPartyIdentity,
  TAccountParty,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    proposerSigner: { value: input.proposerSigner ?? null, isWritable: true },
    proposerIdentity: {
      value: input.proposerIdentity ?? null,
      isWritable: false,
    },
    agreement: { value: input.agreement ?? null, isWritable: true },
    partyIdentity: { value: input.partyIdentity ?? null, isWritable: false },
    party: { value: input.party ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.proposerSigner),
      getAccountMeta(accounts.proposerIdentity),
      getAccountMeta(accounts.agreement),
      getAccountMeta(accounts.partyIdentity),
      getAccountMeta(accounts.party),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getAddPartyInstructionDataEncoder().encode(
      args as AddPartyInstructionDataArgs,
    ),
    programAddress,
  } as AddPartyInstruction<
    TProgramAddress,
    TAccountProposerSigner,
    TAccountProposerIdentity,
    TAccountAgreement,
    TAccountPartyIdentity,
    TAccountParty,
    TAccountSystemProgram
  >);
}

export type ParsedAddPartyInstruction<
  TProgram extends string = typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    proposerSigner: TAccountMetas[0];
    proposerIdentity: TAccountMetas[1];
    agreement: TAccountMetas[2];
    /** The AgentIdentity of the party being added */
    partyIdentity: TAccountMetas[3];
    party: TAccountMetas[4];
    systemProgram: TAccountMetas[5];
  };
  data: AddPartyInstructionData;
};

export function parseAddPartyInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedAddPartyInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      proposerSigner: getNextAccount(),
      proposerIdentity: getNextAccount(),
      agreement: getNextAccount(),
      partyIdentity: getNextAccount(),
      party: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getAddPartyInstructionDataDecoder().decode(instruction.data),
  };
}
