/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS } from "../programs";
import {
  expectSome,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const CANCEL_AGREEMENT_DISCRIMINATOR = new Uint8Array([
  75, 89, 85, 4, 100, 216, 143, 37,
]);

export function getCancelAgreementDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CANCEL_AGREEMENT_DISCRIMINATOR,
  );
}

export type CancelAgreementInstruction<
  TProgram extends string = typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountProposerIdentity extends string | AccountMeta<string> = string,
  TAccountAgreement extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? ReadonlySignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountProposerIdentity extends string
        ? ReadonlyAccount<TAccountProposerIdentity>
        : TAccountProposerIdentity,
      TAccountAgreement extends string
        ? WritableAccount<TAccountAgreement>
        : TAccountAgreement,
      ...TRemainingAccounts,
    ]
  >;

export type CancelAgreementInstructionData = {
  discriminator: ReadonlyUint8Array;
  agreementId: ReadonlyUint8Array;
};

export type CancelAgreementInstructionDataArgs = {
  agreementId: ReadonlyUint8Array;
};

export function getCancelAgreementInstructionDataEncoder(): FixedSizeEncoder<CancelAgreementInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["agreementId", fixEncoderSize(getBytesEncoder(), 16)],
    ]),
    (value) => ({ ...value, discriminator: CANCEL_AGREEMENT_DISCRIMINATOR }),
  );
}

export function getCancelAgreementInstructionDataDecoder(): FixedSizeDecoder<CancelAgreementInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["agreementId", fixDecoderSize(getBytesDecoder(), 16)],
  ]);
}

export function getCancelAgreementInstructionDataCodec(): FixedSizeCodec<
  CancelAgreementInstructionDataArgs,
  CancelAgreementInstructionData
> {
  return combineCodec(
    getCancelAgreementInstructionDataEncoder(),
    getCancelAgreementInstructionDataDecoder(),
  );
}

export type CancelAgreementAsyncInput<
  TAccountSigner extends string = string,
  TAccountProposerIdentity extends string = string,
  TAccountAgreement extends string = string,
> = {
  signer: TransactionSigner<TAccountSigner>;
  /** Proposer's AgentIdentity — signer must be the agent_key or authority */
  proposerIdentity: Address<TAccountProposerIdentity>;
  agreement?: Address<TAccountAgreement>;
  agreementId: CancelAgreementInstructionDataArgs["agreementId"];
};

export async function getCancelAgreementInstructionAsync<
  TAccountSigner extends string,
  TAccountProposerIdentity extends string,
  TAccountAgreement extends string,
  TProgramAddress extends Address =
    typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
>(
  input: CancelAgreementAsyncInput<
    TAccountSigner,
    TAccountProposerIdentity,
    TAccountAgreement
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  CancelAgreementInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountProposerIdentity,
    TAccountAgreement
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: false },
    proposerIdentity: {
      value: input.proposerIdentity ?? null,
      isWritable: false,
    },
    agreement: { value: input.agreement ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.agreement.value) {
    accounts.agreement.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([97, 103, 114, 101, 101, 109, 101, 110, 116]),
        ),
        fixEncoderSize(getBytesEncoder(), 16).encode(
          expectSome(args.agreementId),
        ),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.proposerIdentity),
      getAccountMeta(accounts.agreement),
    ],
    data: getCancelAgreementInstructionDataEncoder().encode(
      args as CancelAgreementInstructionDataArgs,
    ),
    programAddress,
  } as CancelAgreementInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountProposerIdentity,
    TAccountAgreement
  >);
}

export type CancelAgreementInput<
  TAccountSigner extends string = string,
  TAccountProposerIdentity extends string = string,
  TAccountAgreement extends string = string,
> = {
  signer: TransactionSigner<TAccountSigner>;
  /** Proposer's AgentIdentity — signer must be the agent_key or authority */
  proposerIdentity: Address<TAccountProposerIdentity>;
  agreement: Address<TAccountAgreement>;
  agreementId: CancelAgreementInstructionDataArgs["agreementId"];
};

export function getCancelAgreementInstruction<
  TAccountSigner extends string,
  TAccountProposerIdentity extends string,
  TAccountAgreement extends string,
  TProgramAddress extends Address =
    typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
>(
  input: CancelAgreementInput<
    TAccountSigner,
    TAccountProposerIdentity,
    TAccountAgreement
  >,
  config?: { programAddress?: TProgramAddress },
): CancelAgreementInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountProposerIdentity,
  TAccountAgreement
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: false },
    proposerIdentity: {
      value: input.proposerIdentity ?? null,
      isWritable: false,
    },
    agreement: { value: input.agreement ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.proposerIdentity),
      getAccountMeta(accounts.agreement),
    ],
    data: getCancelAgreementInstructionDataEncoder().encode(
      args as CancelAgreementInstructionDataArgs,
    ),
    programAddress,
  } as CancelAgreementInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountProposerIdentity,
    TAccountAgreement
  >);
}

export type ParsedCancelAgreementInstruction<
  TProgram extends string = typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    signer: TAccountMetas[0];
    /** Proposer's AgentIdentity — signer must be the agent_key or authority */
    proposerIdentity: TAccountMetas[1];
    agreement: TAccountMetas[2];
  };
  data: CancelAgreementInstructionData;
};

export function parseCancelAgreementInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCancelAgreementInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      signer: getNextAccount(),
      proposerIdentity: getNextAccount(),
      agreement: getNextAccount(),
    },
    data: getCancelAgreementInstructionDataDecoder().decode(instruction.data),
  };
}
