/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  expectSome,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const CLOSE_AGREEMENT_DISCRIMINATOR = new Uint8Array([
  48, 34, 42, 18, 144, 209, 198, 55,
]);

export function getCloseAgreementDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CLOSE_AGREEMENT_DISCRIMINATOR,
  );
}

export type CloseAgreementInstruction<
  TProgram extends string = typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountSignerIdentity extends string | AccountMeta<string> = string,
  TAccountSignerParty extends string | AccountMeta<string> = string,
  TAccountAgreement extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountSignerIdentity extends string
        ? ReadonlyAccount<TAccountSignerIdentity>
        : TAccountSignerIdentity,
      TAccountSignerParty extends string
        ? WritableAccount<TAccountSignerParty>
        : TAccountSignerParty,
      TAccountAgreement extends string
        ? WritableAccount<TAccountAgreement>
        : TAccountAgreement,
      ...TRemainingAccounts,
    ]
  >;

export type CloseAgreementInstructionData = {
  discriminator: ReadonlyUint8Array;
  agreementId: ReadonlyUint8Array;
};

export type CloseAgreementInstructionDataArgs = {
  agreementId: ReadonlyUint8Array;
};

export function getCloseAgreementInstructionDataEncoder(): FixedSizeEncoder<CloseAgreementInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["agreementId", fixEncoderSize(getBytesEncoder(), 16)],
    ]),
    (value) => ({ ...value, discriminator: CLOSE_AGREEMENT_DISCRIMINATOR }),
  );
}

export function getCloseAgreementInstructionDataDecoder(): FixedSizeDecoder<CloseAgreementInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["agreementId", fixDecoderSize(getBytesDecoder(), 16)],
  ]);
}

export function getCloseAgreementInstructionDataCodec(): FixedSizeCodec<
  CloseAgreementInstructionDataArgs,
  CloseAgreementInstructionData
> {
  return combineCodec(
    getCloseAgreementInstructionDataEncoder(),
    getCloseAgreementInstructionDataDecoder(),
  );
}

export type CloseAgreementAsyncInput<
  TAccountSigner extends string = string,
  TAccountSignerIdentity extends string = string,
  TAccountSignerParty extends string = string,
  TAccountAgreement extends string = string,
> = {
  signer: TransactionSigner<TAccountSigner>;
  /** Signer's AgentIdentity — signer must be the authority */
  signerIdentity: Address<TAccountSignerIdentity>;
  /** Signer must be a party to the agreement */
  signerParty?: Address<TAccountSignerParty>;
  agreement?: Address<TAccountAgreement>;
  agreementId: CloseAgreementInstructionDataArgs["agreementId"];
};

export async function getCloseAgreementInstructionAsync<
  TAccountSigner extends string,
  TAccountSignerIdentity extends string,
  TAccountSignerParty extends string,
  TAccountAgreement extends string,
  TProgramAddress extends Address =
    typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
>(
  input: CloseAgreementAsyncInput<
    TAccountSigner,
    TAccountSignerIdentity,
    TAccountSignerParty,
    TAccountAgreement
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  CloseAgreementInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountSignerIdentity,
    TAccountSignerParty,
    TAccountAgreement
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    signerIdentity: { value: input.signerIdentity ?? null, isWritable: false },
    signerParty: { value: input.signerParty ?? null, isWritable: true },
    agreement: { value: input.agreement ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.signerParty.value) {
    accounts.signerParty.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([112, 97, 114, 116, 121])),
        fixEncoderSize(getBytesEncoder(), 16).encode(
          expectSome(args.agreementId),
        ),
        getAddressEncoder().encode(
          expectAddress(accounts.signerIdentity.value),
        ),
      ],
    });
  }
  if (!accounts.agreement.value) {
    accounts.agreement.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([97, 103, 114, 101, 101, 109, 101, 110, 116]),
        ),
        fixEncoderSize(getBytesEncoder(), 16).encode(
          expectSome(args.agreementId),
        ),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.signerIdentity),
      getAccountMeta(accounts.signerParty),
      getAccountMeta(accounts.agreement),
    ],
    data: getCloseAgreementInstructionDataEncoder().encode(
      args as CloseAgreementInstructionDataArgs,
    ),
    programAddress,
  } as CloseAgreementInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountSignerIdentity,
    TAccountSignerParty,
    TAccountAgreement
  >);
}

export type CloseAgreementInput<
  TAccountSigner extends string = string,
  TAccountSignerIdentity extends string = string,
  TAccountSignerParty extends string = string,
  TAccountAgreement extends string = string,
> = {
  signer: TransactionSigner<TAccountSigner>;
  /** Signer's AgentIdentity — signer must be the authority */
  signerIdentity: Address<TAccountSignerIdentity>;
  /** Signer must be a party to the agreement */
  signerParty: Address<TAccountSignerParty>;
  agreement: Address<TAccountAgreement>;
  agreementId: CloseAgreementInstructionDataArgs["agreementId"];
};

export function getCloseAgreementInstruction<
  TAccountSigner extends string,
  TAccountSignerIdentity extends string,
  TAccountSignerParty extends string,
  TAccountAgreement extends string,
  TProgramAddress extends Address =
    typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
>(
  input: CloseAgreementInput<
    TAccountSigner,
    TAccountSignerIdentity,
    TAccountSignerParty,
    TAccountAgreement
  >,
  config?: { programAddress?: TProgramAddress },
): CloseAgreementInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountSignerIdentity,
  TAccountSignerParty,
  TAccountAgreement
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    signerIdentity: { value: input.signerIdentity ?? null, isWritable: false },
    signerParty: { value: input.signerParty ?? null, isWritable: true },
    agreement: { value: input.agreement ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.signerIdentity),
      getAccountMeta(accounts.signerParty),
      getAccountMeta(accounts.agreement),
    ],
    data: getCloseAgreementInstructionDataEncoder().encode(
      args as CloseAgreementInstructionDataArgs,
    ),
    programAddress,
  } as CloseAgreementInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountSignerIdentity,
    TAccountSignerParty,
    TAccountAgreement
  >);
}

export type ParsedCloseAgreementInstruction<
  TProgram extends string = typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    signer: TAccountMetas[0];
    /** Signer's AgentIdentity — signer must be the authority */
    signerIdentity: TAccountMetas[1];
    /** Signer must be a party to the agreement */
    signerParty: TAccountMetas[2];
    agreement: TAccountMetas[3];
  };
  data: CloseAgreementInstructionData;
};

export function parseCloseAgreementInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCloseAgreementInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      signer: getNextAccount(),
      signerIdentity: getNextAccount(),
      signerParty: getNextAccount(),
      agreement: getNextAccount(),
    },
    data: getCloseAgreementInstructionDataDecoder().decode(instruction.data),
  };
}
