/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  expectSome,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const PROPOSE_AGREEMENT_DISCRIMINATOR = new Uint8Array([
  225, 187, 165, 37, 49, 191, 189, 11,
]);

export function getProposeAgreementDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    PROPOSE_AGREEMENT_DISCRIMINATOR,
  );
}

export type ProposeAgreementInstruction<
  TProgram extends string = typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
  TAccountProposerSigner extends string | AccountMeta<string> = string,
  TAccountProposerIdentity extends string | AccountMeta<string> = string,
  TAccountAgreement extends string | AccountMeta<string> = string,
  TAccountProposerParty extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountProposerSigner extends string
        ? WritableSignerAccount<TAccountProposerSigner> &
            AccountSignerMeta<TAccountProposerSigner>
        : TAccountProposerSigner,
      TAccountProposerIdentity extends string
        ? ReadonlyAccount<TAccountProposerIdentity>
        : TAccountProposerIdentity,
      TAccountAgreement extends string
        ? WritableAccount<TAccountAgreement>
        : TAccountAgreement,
      TAccountProposerParty extends string
        ? WritableAccount<TAccountProposerParty>
        : TAccountProposerParty,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type ProposeAgreementInstructionData = {
  discriminator: ReadonlyUint8Array;
  agreementId: ReadonlyUint8Array;
  agreementType: number;
  visibility: number;
  termsHash: ReadonlyUint8Array;
  termsUri: ReadonlyUint8Array;
  numParties: number;
  expiresAt: bigint;
};

export type ProposeAgreementInstructionDataArgs = {
  agreementId: ReadonlyUint8Array;
  agreementType: number;
  visibility: number;
  termsHash: ReadonlyUint8Array;
  termsUri: ReadonlyUint8Array;
  numParties: number;
  expiresAt: number | bigint;
};

export function getProposeAgreementInstructionDataEncoder(): FixedSizeEncoder<ProposeAgreementInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["agreementId", fixEncoderSize(getBytesEncoder(), 16)],
      ["agreementType", getU8Encoder()],
      ["visibility", getU8Encoder()],
      ["termsHash", fixEncoderSize(getBytesEncoder(), 32)],
      ["termsUri", fixEncoderSize(getBytesEncoder(), 64)],
      ["numParties", getU8Encoder()],
      ["expiresAt", getI64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: PROPOSE_AGREEMENT_DISCRIMINATOR }),
  );
}

export function getProposeAgreementInstructionDataDecoder(): FixedSizeDecoder<ProposeAgreementInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["agreementId", fixDecoderSize(getBytesDecoder(), 16)],
    ["agreementType", getU8Decoder()],
    ["visibility", getU8Decoder()],
    ["termsHash", fixDecoderSize(getBytesDecoder(), 32)],
    ["termsUri", fixDecoderSize(getBytesDecoder(), 64)],
    ["numParties", getU8Decoder()],
    ["expiresAt", getI64Decoder()],
  ]);
}

export function getProposeAgreementInstructionDataCodec(): FixedSizeCodec<
  ProposeAgreementInstructionDataArgs,
  ProposeAgreementInstructionData
> {
  return combineCodec(
    getProposeAgreementInstructionDataEncoder(),
    getProposeAgreementInstructionDataDecoder(),
  );
}

export type ProposeAgreementAsyncInput<
  TAccountProposerSigner extends string = string,
  TAccountProposerIdentity extends string = string,
  TAccountAgreement extends string = string,
  TAccountProposerParty extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  proposerSigner: TransactionSigner<TAccountProposerSigner>;
  proposerIdentity: Address<TAccountProposerIdentity>;
  agreement?: Address<TAccountAgreement>;
  proposerParty?: Address<TAccountProposerParty>;
  systemProgram?: Address<TAccountSystemProgram>;
  agreementId: ProposeAgreementInstructionDataArgs["agreementId"];
  agreementType: ProposeAgreementInstructionDataArgs["agreementType"];
  visibility: ProposeAgreementInstructionDataArgs["visibility"];
  termsHash: ProposeAgreementInstructionDataArgs["termsHash"];
  termsUri: ProposeAgreementInstructionDataArgs["termsUri"];
  numParties: ProposeAgreementInstructionDataArgs["numParties"];
  expiresAt: ProposeAgreementInstructionDataArgs["expiresAt"];
};

export async function getProposeAgreementInstructionAsync<
  TAccountProposerSigner extends string,
  TAccountProposerIdentity extends string,
  TAccountAgreement extends string,
  TAccountProposerParty extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address =
    typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
>(
  input: ProposeAgreementAsyncInput<
    TAccountProposerSigner,
    TAccountProposerIdentity,
    TAccountAgreement,
    TAccountProposerParty,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  ProposeAgreementInstruction<
    TProgramAddress,
    TAccountProposerSigner,
    TAccountProposerIdentity,
    TAccountAgreement,
    TAccountProposerParty,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    proposerSigner: { value: input.proposerSigner ?? null, isWritable: true },
    proposerIdentity: {
      value: input.proposerIdentity ?? null,
      isWritable: false,
    },
    agreement: { value: input.agreement ?? null, isWritable: true },
    proposerParty: { value: input.proposerParty ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.agreement.value) {
    accounts.agreement.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([97, 103, 114, 101, 101, 109, 101, 110, 116]),
        ),
        fixEncoderSize(getBytesEncoder(), 16).encode(
          expectSome(args.agreementId),
        ),
      ],
    });
  }
  if (!accounts.proposerParty.value) {
    accounts.proposerParty.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([112, 97, 114, 116, 121])),
        fixEncoderSize(getBytesEncoder(), 16).encode(
          expectSome(args.agreementId),
        ),
        getAddressEncoder().encode(
          expectAddress(accounts.proposerIdentity.value),
        ),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.proposerSigner),
      getAccountMeta(accounts.proposerIdentity),
      getAccountMeta(accounts.agreement),
      getAccountMeta(accounts.proposerParty),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getProposeAgreementInstructionDataEncoder().encode(
      args as ProposeAgreementInstructionDataArgs,
    ),
    programAddress,
  } as ProposeAgreementInstruction<
    TProgramAddress,
    TAccountProposerSigner,
    TAccountProposerIdentity,
    TAccountAgreement,
    TAccountProposerParty,
    TAccountSystemProgram
  >);
}

export type ProposeAgreementInput<
  TAccountProposerSigner extends string = string,
  TAccountProposerIdentity extends string = string,
  TAccountAgreement extends string = string,
  TAccountProposerParty extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  proposerSigner: TransactionSigner<TAccountProposerSigner>;
  proposerIdentity: Address<TAccountProposerIdentity>;
  agreement: Address<TAccountAgreement>;
  proposerParty: Address<TAccountProposerParty>;
  systemProgram?: Address<TAccountSystemProgram>;
  agreementId: ProposeAgreementInstructionDataArgs["agreementId"];
  agreementType: ProposeAgreementInstructionDataArgs["agreementType"];
  visibility: ProposeAgreementInstructionDataArgs["visibility"];
  termsHash: ProposeAgreementInstructionDataArgs["termsHash"];
  termsUri: ProposeAgreementInstructionDataArgs["termsUri"];
  numParties: ProposeAgreementInstructionDataArgs["numParties"];
  expiresAt: ProposeAgreementInstructionDataArgs["expiresAt"];
};

export function getProposeAgreementInstruction<
  TAccountProposerSigner extends string,
  TAccountProposerIdentity extends string,
  TAccountAgreement extends string,
  TAccountProposerParty extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address =
    typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
>(
  input: ProposeAgreementInput<
    TAccountProposerSigner,
    TAccountProposerIdentity,
    TAccountAgreement,
    TAccountProposerParty,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): ProposeAgreementInstruction<
  TProgramAddress,
  TAccountProposerSigner,
  TAccountProposerIdentity,
  TAccountAgreement,
  TAccountProposerParty,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    proposerSigner: { value: input.proposerSigner ?? null, isWritable: true },
    proposerIdentity: {
      value: input.proposerIdentity ?? null,
      isWritable: false,
    },
    agreement: { value: input.agreement ?? null, isWritable: true },
    proposerParty: { value: input.proposerParty ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.proposerSigner),
      getAccountMeta(accounts.proposerIdentity),
      getAccountMeta(accounts.agreement),
      getAccountMeta(accounts.proposerParty),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getProposeAgreementInstructionDataEncoder().encode(
      args as ProposeAgreementInstructionDataArgs,
    ),
    programAddress,
  } as ProposeAgreementInstruction<
    TProgramAddress,
    TAccountProposerSigner,
    TAccountProposerIdentity,
    TAccountAgreement,
    TAccountProposerParty,
    TAccountSystemProgram
  >);
}

export type ParsedProposeAgreementInstruction<
  TProgram extends string = typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    proposerSigner: TAccountMetas[0];
    proposerIdentity: TAccountMetas[1];
    agreement: TAccountMetas[2];
    proposerParty: TAccountMetas[3];
    systemProgram: TAccountMetas[4];
  };
  data: ProposeAgreementInstructionData;
};

export function parseProposeAgreementInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedProposeAgreementInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      proposerSigner: getNextAccount(),
      proposerIdentity: getNextAccount(),
      agreement: getNextAccount(),
      proposerParty: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getProposeAgreementInstructionDataDecoder().decode(instruction.data),
  };
}
