/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS } from "../programs";
import {
  expectSome,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";
import {
  getDelegationScopeDecoder,
  getDelegationScopeEncoder,
  type DelegationScope,
  type DelegationScopeArgs,
} from "../types";

export const REGISTER_AGENT_DISCRIMINATOR = new Uint8Array([
  135, 157, 66, 195, 2, 113, 175, 30,
]);

export function getRegisterAgentDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    REGISTER_AGENT_DISCRIMINATOR,
  );
}

export type RegisterAgentInstruction<
  TProgram extends string = typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountAgentIdentity extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountAgentIdentity extends string
        ? WritableAccount<TAccountAgentIdentity>
        : TAccountAgentIdentity,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type RegisterAgentInstructionData = {
  discriminator: ReadonlyUint8Array;
  agentKey: Address;
  metadataHash: ReadonlyUint8Array;
  scope: DelegationScope;
};

export type RegisterAgentInstructionDataArgs = {
  agentKey: Address;
  metadataHash: ReadonlyUint8Array;
  scope: DelegationScopeArgs;
};

export function getRegisterAgentInstructionDataEncoder(): FixedSizeEncoder<RegisterAgentInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["agentKey", getAddressEncoder()],
      ["metadataHash", fixEncoderSize(getBytesEncoder(), 32)],
      ["scope", getDelegationScopeEncoder()],
    ]),
    (value) => ({ ...value, discriminator: REGISTER_AGENT_DISCRIMINATOR }),
  );
}

export function getRegisterAgentInstructionDataDecoder(): FixedSizeDecoder<RegisterAgentInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["agentKey", getAddressDecoder()],
    ["metadataHash", fixDecoderSize(getBytesDecoder(), 32)],
    ["scope", getDelegationScopeDecoder()],
  ]);
}

export function getRegisterAgentInstructionDataCodec(): FixedSizeCodec<
  RegisterAgentInstructionDataArgs,
  RegisterAgentInstructionData
> {
  return combineCodec(
    getRegisterAgentInstructionDataEncoder(),
    getRegisterAgentInstructionDataDecoder(),
  );
}

export type RegisterAgentAsyncInput<
  TAccountAuthority extends string = string,
  TAccountAgentIdentity extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  agentIdentity?: Address<TAccountAgentIdentity>;
  systemProgram?: Address<TAccountSystemProgram>;
  agentKey: RegisterAgentInstructionDataArgs["agentKey"];
  metadataHash: RegisterAgentInstructionDataArgs["metadataHash"];
  scope: RegisterAgentInstructionDataArgs["scope"];
};

export async function getRegisterAgentInstructionAsync<
  TAccountAuthority extends string,
  TAccountAgentIdentity extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address =
    typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
>(
  input: RegisterAgentAsyncInput<
    TAccountAuthority,
    TAccountAgentIdentity,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  RegisterAgentInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountAgentIdentity,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    agentIdentity: { value: input.agentIdentity ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.agentIdentity.value) {
    accounts.agentIdentity.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([97, 103, 101, 110, 116])),
        getAddressEncoder().encode(expectSome(args.agentKey)),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.agentIdentity),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getRegisterAgentInstructionDataEncoder().encode(
      args as RegisterAgentInstructionDataArgs,
    ),
    programAddress,
  } as RegisterAgentInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountAgentIdentity,
    TAccountSystemProgram
  >);
}

export type RegisterAgentInput<
  TAccountAuthority extends string = string,
  TAccountAgentIdentity extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  agentIdentity: Address<TAccountAgentIdentity>;
  systemProgram?: Address<TAccountSystemProgram>;
  agentKey: RegisterAgentInstructionDataArgs["agentKey"];
  metadataHash: RegisterAgentInstructionDataArgs["metadataHash"];
  scope: RegisterAgentInstructionDataArgs["scope"];
};

export function getRegisterAgentInstruction<
  TAccountAuthority extends string,
  TAccountAgentIdentity extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address =
    typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
>(
  input: RegisterAgentInput<
    TAccountAuthority,
    TAccountAgentIdentity,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): RegisterAgentInstruction<
  TProgramAddress,
  TAccountAuthority,
  TAccountAgentIdentity,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    agentIdentity: { value: input.agentIdentity ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.agentIdentity),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getRegisterAgentInstructionDataEncoder().encode(
      args as RegisterAgentInstructionDataArgs,
    ),
    programAddress,
  } as RegisterAgentInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountAgentIdentity,
    TAccountSystemProgram
  >);
}

export type ParsedRegisterAgentInstruction<
  TProgram extends string = typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    authority: TAccountMetas[0];
    agentIdentity: TAccountMetas[1];
    systemProgram: TAccountMetas[2];
  };
  data: RegisterAgentInstructionData;
};

export function parseRegisterAgentInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedRegisterAgentInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      authority: getNextAccount(),
      agentIdentity: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getRegisterAgentInstructionDataDecoder().decode(instruction.data),
  };
}
