/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS } from "../programs";
import {
  expectSome,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";
import {
  getDelegationScopeDecoder,
  getDelegationScopeEncoder,
  type DelegationScope,
  type DelegationScopeArgs,
} from "../types";

export const REGISTER_SUB_AGENT_DISCRIMINATOR = new Uint8Array([
  218, 146, 50, 162, 93, 32, 5, 151,
]);

export function getRegisterSubAgentDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    REGISTER_SUB_AGENT_DISCRIMINATOR,
  );
}

export type RegisterSubAgentInstruction<
  TProgram extends string = typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
  TAccountParentAgentSigner extends string | AccountMeta<string> = string,
  TAccountParentIdentity extends string | AccountMeta<string> = string,
  TAccountSubAgentIdentity extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountParentAgentSigner extends string
        ? WritableSignerAccount<TAccountParentAgentSigner> &
            AccountSignerMeta<TAccountParentAgentSigner>
        : TAccountParentAgentSigner,
      TAccountParentIdentity extends string
        ? ReadonlyAccount<TAccountParentIdentity>
        : TAccountParentIdentity,
      TAccountSubAgentIdentity extends string
        ? WritableAccount<TAccountSubAgentIdentity>
        : TAccountSubAgentIdentity,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type RegisterSubAgentInstructionData = {
  discriminator: ReadonlyUint8Array;
  subAgentKey: Address;
  metadataHash: ReadonlyUint8Array;
  scope: DelegationScope;
};

export type RegisterSubAgentInstructionDataArgs = {
  subAgentKey: Address;
  metadataHash: ReadonlyUint8Array;
  scope: DelegationScopeArgs;
};

export function getRegisterSubAgentInstructionDataEncoder(): FixedSizeEncoder<RegisterSubAgentInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["subAgentKey", getAddressEncoder()],
      ["metadataHash", fixEncoderSize(getBytesEncoder(), 32)],
      ["scope", getDelegationScopeEncoder()],
    ]),
    (value) => ({ ...value, discriminator: REGISTER_SUB_AGENT_DISCRIMINATOR }),
  );
}

export function getRegisterSubAgentInstructionDataDecoder(): FixedSizeDecoder<RegisterSubAgentInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["subAgentKey", getAddressDecoder()],
    ["metadataHash", fixDecoderSize(getBytesDecoder(), 32)],
    ["scope", getDelegationScopeDecoder()],
  ]);
}

export function getRegisterSubAgentInstructionDataCodec(): FixedSizeCodec<
  RegisterSubAgentInstructionDataArgs,
  RegisterSubAgentInstructionData
> {
  return combineCodec(
    getRegisterSubAgentInstructionDataEncoder(),
    getRegisterSubAgentInstructionDataDecoder(),
  );
}

export type RegisterSubAgentAsyncInput<
  TAccountParentAgentSigner extends string = string,
  TAccountParentIdentity extends string = string,
  TAccountSubAgentIdentity extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  parentAgentSigner: TransactionSigner<TAccountParentAgentSigner>;
  parentIdentity: Address<TAccountParentIdentity>;
  subAgentIdentity?: Address<TAccountSubAgentIdentity>;
  systemProgram?: Address<TAccountSystemProgram>;
  subAgentKey: RegisterSubAgentInstructionDataArgs["subAgentKey"];
  metadataHash: RegisterSubAgentInstructionDataArgs["metadataHash"];
  scope: RegisterSubAgentInstructionDataArgs["scope"];
};

export async function getRegisterSubAgentInstructionAsync<
  TAccountParentAgentSigner extends string,
  TAccountParentIdentity extends string,
  TAccountSubAgentIdentity extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address =
    typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
>(
  input: RegisterSubAgentAsyncInput<
    TAccountParentAgentSigner,
    TAccountParentIdentity,
    TAccountSubAgentIdentity,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  RegisterSubAgentInstruction<
    TProgramAddress,
    TAccountParentAgentSigner,
    TAccountParentIdentity,
    TAccountSubAgentIdentity,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    parentAgentSigner: {
      value: input.parentAgentSigner ?? null,
      isWritable: true,
    },
    parentIdentity: { value: input.parentIdentity ?? null, isWritable: false },
    subAgentIdentity: {
      value: input.subAgentIdentity ?? null,
      isWritable: true,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.subAgentIdentity.value) {
    accounts.subAgentIdentity.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([97, 103, 101, 110, 116])),
        getAddressEncoder().encode(expectSome(args.subAgentKey)),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.parentAgentSigner),
      getAccountMeta(accounts.parentIdentity),
      getAccountMeta(accounts.subAgentIdentity),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getRegisterSubAgentInstructionDataEncoder().encode(
      args as RegisterSubAgentInstructionDataArgs,
    ),
    programAddress,
  } as RegisterSubAgentInstruction<
    TProgramAddress,
    TAccountParentAgentSigner,
    TAccountParentIdentity,
    TAccountSubAgentIdentity,
    TAccountSystemProgram
  >);
}

export type RegisterSubAgentInput<
  TAccountParentAgentSigner extends string = string,
  TAccountParentIdentity extends string = string,
  TAccountSubAgentIdentity extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  parentAgentSigner: TransactionSigner<TAccountParentAgentSigner>;
  parentIdentity: Address<TAccountParentIdentity>;
  subAgentIdentity: Address<TAccountSubAgentIdentity>;
  systemProgram?: Address<TAccountSystemProgram>;
  subAgentKey: RegisterSubAgentInstructionDataArgs["subAgentKey"];
  metadataHash: RegisterSubAgentInstructionDataArgs["metadataHash"];
  scope: RegisterSubAgentInstructionDataArgs["scope"];
};

export function getRegisterSubAgentInstruction<
  TAccountParentAgentSigner extends string,
  TAccountParentIdentity extends string,
  TAccountSubAgentIdentity extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address =
    typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
>(
  input: RegisterSubAgentInput<
    TAccountParentAgentSigner,
    TAccountParentIdentity,
    TAccountSubAgentIdentity,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): RegisterSubAgentInstruction<
  TProgramAddress,
  TAccountParentAgentSigner,
  TAccountParentIdentity,
  TAccountSubAgentIdentity,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    parentAgentSigner: {
      value: input.parentAgentSigner ?? null,
      isWritable: true,
    },
    parentIdentity: { value: input.parentIdentity ?? null, isWritable: false },
    subAgentIdentity: {
      value: input.subAgentIdentity ?? null,
      isWritable: true,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.parentAgentSigner),
      getAccountMeta(accounts.parentIdentity),
      getAccountMeta(accounts.subAgentIdentity),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getRegisterSubAgentInstructionDataEncoder().encode(
      args as RegisterSubAgentInstructionDataArgs,
    ),
    programAddress,
  } as RegisterSubAgentInstruction<
    TProgramAddress,
    TAccountParentAgentSigner,
    TAccountParentIdentity,
    TAccountSubAgentIdentity,
    TAccountSystemProgram
  >);
}

export type ParsedRegisterSubAgentInstruction<
  TProgram extends string = typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    parentAgentSigner: TAccountMetas[0];
    parentIdentity: TAccountMetas[1];
    subAgentIdentity: TAccountMetas[2];
    systemProgram: TAccountMetas[3];
  };
  data: RegisterSubAgentInstructionData;
};

export function parseRegisterSubAgentInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedRegisterSubAgentInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      parentAgentSigner: getNextAccount(),
      parentIdentity: getNextAccount(),
      subAgentIdentity: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getRegisterSubAgentInstructionDataDecoder().decode(instruction.data),
  };
}
