/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const REVOKE_AGENT_DISCRIMINATOR = new Uint8Array([
  227, 60, 209, 125, 240, 117, 163, 73,
]);

export function getRevokeAgentDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    REVOKE_AGENT_DISCRIMINATOR,
  );
}

export type RevokeAgentInstruction<
  TProgram extends string = typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountAgentIdentity extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountAgentIdentity extends string
        ? WritableAccount<TAccountAgentIdentity>
        : TAccountAgentIdentity,
      ...TRemainingAccounts,
    ]
  >;

export type RevokeAgentInstructionData = { discriminator: ReadonlyUint8Array };

export type RevokeAgentInstructionDataArgs = {};

export function getRevokeAgentInstructionDataEncoder(): FixedSizeEncoder<RevokeAgentInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: REVOKE_AGENT_DISCRIMINATOR }),
  );
}

export function getRevokeAgentInstructionDataDecoder(): FixedSizeDecoder<RevokeAgentInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getRevokeAgentInstructionDataCodec(): FixedSizeCodec<
  RevokeAgentInstructionDataArgs,
  RevokeAgentInstructionData
> {
  return combineCodec(
    getRevokeAgentInstructionDataEncoder(),
    getRevokeAgentInstructionDataDecoder(),
  );
}

export type RevokeAgentInput<
  TAccountAuthority extends string = string,
  TAccountAgentIdentity extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  agentIdentity: Address<TAccountAgentIdentity>;
};

export function getRevokeAgentInstruction<
  TAccountAuthority extends string,
  TAccountAgentIdentity extends string,
  TProgramAddress extends Address =
    typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
>(
  input: RevokeAgentInput<TAccountAuthority, TAccountAgentIdentity>,
  config?: { programAddress?: TProgramAddress },
): RevokeAgentInstruction<
  TProgramAddress,
  TAccountAuthority,
  TAccountAgentIdentity
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    agentIdentity: { value: input.agentIdentity ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.agentIdentity),
    ],
    data: getRevokeAgentInstructionDataEncoder().encode({}),
    programAddress,
  } as RevokeAgentInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountAgentIdentity
  >);
}

export type ParsedRevokeAgentInstruction<
  TProgram extends string = typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    authority: TAccountMetas[0];
    agentIdentity: TAccountMetas[1];
  };
  data: RevokeAgentInstructionData;
};

export function parseRevokeAgentInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedRevokeAgentInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { authority: getNextAccount(), agentIdentity: getNextAccount() },
    data: getRevokeAgentInstructionDataDecoder().decode(instruction.data),
  };
}
