/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  expectSome,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const SIGN_AGREEMENT_DISCRIMINATOR = new Uint8Array([
  113, 163, 162, 101, 44, 101, 65, 204,
]);

export function getSignAgreementDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    SIGN_AGREEMENT_DISCRIMINATOR,
  );
}

export type SignAgreementInstruction<
  TProgram extends string = typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountSignerIdentity extends string | AccountMeta<string> = string,
  TAccountAgreement extends string | AccountMeta<string> = string,
  TAccountParty extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? ReadonlySignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountSignerIdentity extends string
        ? ReadonlyAccount<TAccountSignerIdentity>
        : TAccountSignerIdentity,
      TAccountAgreement extends string
        ? WritableAccount<TAccountAgreement>
        : TAccountAgreement,
      TAccountParty extends string
        ? WritableAccount<TAccountParty>
        : TAccountParty,
      ...TRemainingAccounts,
    ]
  >;

export type SignAgreementInstructionData = {
  discriminator: ReadonlyUint8Array;
  agreementId: ReadonlyUint8Array;
};

export type SignAgreementInstructionDataArgs = {
  agreementId: ReadonlyUint8Array;
};

export function getSignAgreementInstructionDataEncoder(): FixedSizeEncoder<SignAgreementInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["agreementId", fixEncoderSize(getBytesEncoder(), 16)],
    ]),
    (value) => ({ ...value, discriminator: SIGN_AGREEMENT_DISCRIMINATOR }),
  );
}

export function getSignAgreementInstructionDataDecoder(): FixedSizeDecoder<SignAgreementInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["agreementId", fixDecoderSize(getBytesDecoder(), 16)],
  ]);
}

export function getSignAgreementInstructionDataCodec(): FixedSizeCodec<
  SignAgreementInstructionDataArgs,
  SignAgreementInstructionData
> {
  return combineCodec(
    getSignAgreementInstructionDataEncoder(),
    getSignAgreementInstructionDataDecoder(),
  );
}

export type SignAgreementAsyncInput<
  TAccountSigner extends string = string,
  TAccountSignerIdentity extends string = string,
  TAccountAgreement extends string = string,
  TAccountParty extends string = string,
> = {
  signer: TransactionSigner<TAccountSigner>;
  signerIdentity: Address<TAccountSignerIdentity>;
  agreement?: Address<TAccountAgreement>;
  party?: Address<TAccountParty>;
  agreementId: SignAgreementInstructionDataArgs["agreementId"];
};

export async function getSignAgreementInstructionAsync<
  TAccountSigner extends string,
  TAccountSignerIdentity extends string,
  TAccountAgreement extends string,
  TAccountParty extends string,
  TProgramAddress extends Address =
    typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
>(
  input: SignAgreementAsyncInput<
    TAccountSigner,
    TAccountSignerIdentity,
    TAccountAgreement,
    TAccountParty
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  SignAgreementInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountSignerIdentity,
    TAccountAgreement,
    TAccountParty
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: false },
    signerIdentity: { value: input.signerIdentity ?? null, isWritable: false },
    agreement: { value: input.agreement ?? null, isWritable: true },
    party: { value: input.party ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.agreement.value) {
    accounts.agreement.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([97, 103, 114, 101, 101, 109, 101, 110, 116]),
        ),
        fixEncoderSize(getBytesEncoder(), 16).encode(
          expectSome(args.agreementId),
        ),
      ],
    });
  }
  if (!accounts.party.value) {
    accounts.party.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([112, 97, 114, 116, 121])),
        fixEncoderSize(getBytesEncoder(), 16).encode(
          expectSome(args.agreementId),
        ),
        getAddressEncoder().encode(
          expectAddress(accounts.signerIdentity.value),
        ),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.signerIdentity),
      getAccountMeta(accounts.agreement),
      getAccountMeta(accounts.party),
    ],
    data: getSignAgreementInstructionDataEncoder().encode(
      args as SignAgreementInstructionDataArgs,
    ),
    programAddress,
  } as SignAgreementInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountSignerIdentity,
    TAccountAgreement,
    TAccountParty
  >);
}

export type SignAgreementInput<
  TAccountSigner extends string = string,
  TAccountSignerIdentity extends string = string,
  TAccountAgreement extends string = string,
  TAccountParty extends string = string,
> = {
  signer: TransactionSigner<TAccountSigner>;
  signerIdentity: Address<TAccountSignerIdentity>;
  agreement: Address<TAccountAgreement>;
  party: Address<TAccountParty>;
  agreementId: SignAgreementInstructionDataArgs["agreementId"];
};

export function getSignAgreementInstruction<
  TAccountSigner extends string,
  TAccountSignerIdentity extends string,
  TAccountAgreement extends string,
  TAccountParty extends string,
  TProgramAddress extends Address =
    typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
>(
  input: SignAgreementInput<
    TAccountSigner,
    TAccountSignerIdentity,
    TAccountAgreement,
    TAccountParty
  >,
  config?: { programAddress?: TProgramAddress },
): SignAgreementInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountSignerIdentity,
  TAccountAgreement,
  TAccountParty
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: false },
    signerIdentity: { value: input.signerIdentity ?? null, isWritable: false },
    agreement: { value: input.agreement ?? null, isWritable: true },
    party: { value: input.party ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.signerIdentity),
      getAccountMeta(accounts.agreement),
      getAccountMeta(accounts.party),
    ],
    data: getSignAgreementInstructionDataEncoder().encode(
      args as SignAgreementInstructionDataArgs,
    ),
    programAddress,
  } as SignAgreementInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountSignerIdentity,
    TAccountAgreement,
    TAccountParty
  >);
}

export type ParsedSignAgreementInstruction<
  TProgram extends string = typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    signer: TAccountMetas[0];
    signerIdentity: TAccountMetas[1];
    agreement: TAccountMetas[2];
    party: TAccountMetas[3];
  };
  data: SignAgreementInstructionData;
};

export function parseSignAgreementInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedSignAgreementInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      signer: getNextAccount(),
      signerIdentity: getNextAccount(),
      agreement: getNextAccount(),
      party: getNextAccount(),
    },
    data: getSignAgreementInstructionDataDecoder().decode(instruction.data),
  };
}
