/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";
import {
  getDelegationScopeDecoder,
  getDelegationScopeEncoder,
  type DelegationScope,
  type DelegationScopeArgs,
} from "../types";

export const UPDATE_DELEGATION_DISCRIMINATOR = new Uint8Array([
  87, 91, 130, 42, 18, 37, 155, 70,
]);

export function getUpdateDelegationDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_DELEGATION_DISCRIMINATOR,
  );
}

export type UpdateDelegationInstruction<
  TProgram extends string = typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountAgentIdentity extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountAgentIdentity extends string
        ? WritableAccount<TAccountAgentIdentity>
        : TAccountAgentIdentity,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateDelegationInstructionData = {
  discriminator: ReadonlyUint8Array;
  newScope: DelegationScope;
};

export type UpdateDelegationInstructionDataArgs = {
  newScope: DelegationScopeArgs;
};

export function getUpdateDelegationInstructionDataEncoder(): FixedSizeEncoder<UpdateDelegationInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["newScope", getDelegationScopeEncoder()],
    ]),
    (value) => ({ ...value, discriminator: UPDATE_DELEGATION_DISCRIMINATOR }),
  );
}

export function getUpdateDelegationInstructionDataDecoder(): FixedSizeDecoder<UpdateDelegationInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["newScope", getDelegationScopeDecoder()],
  ]);
}

export function getUpdateDelegationInstructionDataCodec(): FixedSizeCodec<
  UpdateDelegationInstructionDataArgs,
  UpdateDelegationInstructionData
> {
  return combineCodec(
    getUpdateDelegationInstructionDataEncoder(),
    getUpdateDelegationInstructionDataDecoder(),
  );
}

export type UpdateDelegationInput<
  TAccountAuthority extends string = string,
  TAccountAgentIdentity extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  agentIdentity: Address<TAccountAgentIdentity>;
  newScope: UpdateDelegationInstructionDataArgs["newScope"];
};

export function getUpdateDelegationInstruction<
  TAccountAuthority extends string,
  TAccountAgentIdentity extends string,
  TProgramAddress extends Address =
    typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
>(
  input: UpdateDelegationInput<TAccountAuthority, TAccountAgentIdentity>,
  config?: { programAddress?: TProgramAddress },
): UpdateDelegationInstruction<
  TProgramAddress,
  TAccountAuthority,
  TAccountAgentIdentity
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: false },
    agentIdentity: { value: input.agentIdentity ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.agentIdentity),
    ],
    data: getUpdateDelegationInstructionDataEncoder().encode(
      args as UpdateDelegationInstructionDataArgs,
    ),
    programAddress,
  } as UpdateDelegationInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountAgentIdentity
  >);
}

export type ParsedUpdateDelegationInstruction<
  TProgram extends string = typeof AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    authority: TAccountMetas[0];
    agentIdentity: TAccountMetas[1];
  };
  data: UpdateDelegationInstructionData;
};

export function parseUpdateDelegationInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedUpdateDelegationInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { authority: getNextAccount(), agentIdentity: getNextAccount() },
    data: getUpdateDelegationInstructionDataDecoder().decode(instruction.data),
  };
}
