/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getDelegationScopeDecoder,
  getDelegationScopeEncoder,
  type DelegationScope,
  type DelegationScopeArgs,
} from "../types";

export const AGENT_IDENTITY_DISCRIMINATOR = new Uint8Array([
  11, 149, 31, 27, 186, 76, 241, 72,
]);

export function getAgentIdentityDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    AGENT_IDENTITY_DISCRIMINATOR,
  );
}

export type AgentIdentity = {
  discriminator: ReadonlyUint8Array;
  authority: Address;
  agentKey: Address;
  metadataHash: ReadonlyUint8Array;
  scope: DelegationScope;
  parent: Address;
  createdAt: bigint;
  bump: number;
};

export type AgentIdentityArgs = {
  authority: Address;
  agentKey: Address;
  metadataHash: ReadonlyUint8Array;
  scope: DelegationScopeArgs;
  parent: Address;
  createdAt: number | bigint;
  bump: number;
};

/** Gets the encoder for {@link AgentIdentityArgs} account data. */
export function getAgentIdentityEncoder(): FixedSizeEncoder<AgentIdentityArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["authority", getAddressEncoder()],
      ["agentKey", getAddressEncoder()],
      ["metadataHash", fixEncoderSize(getBytesEncoder(), 32)],
      ["scope", getDelegationScopeEncoder()],
      ["parent", getAddressEncoder()],
      ["createdAt", getI64Encoder()],
      ["bump", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: AGENT_IDENTITY_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link AgentIdentity} account data. */
export function getAgentIdentityDecoder(): FixedSizeDecoder<AgentIdentity> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["authority", getAddressDecoder()],
    ["agentKey", getAddressDecoder()],
    ["metadataHash", fixDecoderSize(getBytesDecoder(), 32)],
    ["scope", getDelegationScopeDecoder()],
    ["parent", getAddressDecoder()],
    ["createdAt", getI64Decoder()],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link AgentIdentity} account data. */
export function getAgentIdentityCodec(): FixedSizeCodec<
  AgentIdentityArgs,
  AgentIdentity
> {
  return combineCodec(getAgentIdentityEncoder(), getAgentIdentityDecoder());
}

export function decodeAgentIdentity<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<AgentIdentity, TAddress>;
export function decodeAgentIdentity<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<AgentIdentity, TAddress>;
export function decodeAgentIdentity<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<AgentIdentity, TAddress> | MaybeAccount<AgentIdentity, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getAgentIdentityDecoder(),
  );
}

export async function fetchAgentIdentity<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<AgentIdentity, TAddress>> {
  const maybeAccount = await fetchMaybeAgentIdentity(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeAgentIdentity<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<AgentIdentity, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeAgentIdentity(maybeAccount);
}

export async function fetchAllAgentIdentity(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<AgentIdentity>[]> {
  const maybeAccounts = await fetchAllMaybeAgentIdentity(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeAgentIdentity(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<AgentIdentity>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeAgentIdentity(maybeAccount));
}

export function getAgentIdentitySize(): number {
  return 163;
}
