/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const AGREEMENT_PARTY_DISCRIMINATOR = new Uint8Array([
  126, 203, 208, 120, 149, 204, 109, 16,
]);

export function getAgreementPartyDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    AGREEMENT_PARTY_DISCRIMINATOR,
  );
}

export type AgreementParty = {
  discriminator: ReadonlyUint8Array;
  agreement: Address;
  agentIdentity: Address;
  role: number;
  signed: boolean;
  signedAt: bigint;
  escrowDeposited: bigint;
  bump: number;
};

export type AgreementPartyArgs = {
  agreement: Address;
  agentIdentity: Address;
  role: number;
  signed: boolean;
  signedAt: number | bigint;
  escrowDeposited: number | bigint;
  bump: number;
};

/** Gets the encoder for {@link AgreementPartyArgs} account data. */
export function getAgreementPartyEncoder(): FixedSizeEncoder<AgreementPartyArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["agreement", getAddressEncoder()],
      ["agentIdentity", getAddressEncoder()],
      ["role", getU8Encoder()],
      ["signed", getBooleanEncoder()],
      ["signedAt", getI64Encoder()],
      ["escrowDeposited", getU64Encoder()],
      ["bump", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: AGREEMENT_PARTY_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link AgreementParty} account data. */
export function getAgreementPartyDecoder(): FixedSizeDecoder<AgreementParty> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["agreement", getAddressDecoder()],
    ["agentIdentity", getAddressDecoder()],
    ["role", getU8Decoder()],
    ["signed", getBooleanDecoder()],
    ["signedAt", getI64Decoder()],
    ["escrowDeposited", getU64Decoder()],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link AgreementParty} account data. */
export function getAgreementPartyCodec(): FixedSizeCodec<
  AgreementPartyArgs,
  AgreementParty
> {
  return combineCodec(getAgreementPartyEncoder(), getAgreementPartyDecoder());
}

export function decodeAgreementParty<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<AgreementParty, TAddress>;
export function decodeAgreementParty<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<AgreementParty, TAddress>;
export function decodeAgreementParty<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<AgreementParty, TAddress> | MaybeAccount<AgreementParty, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getAgreementPartyDecoder(),
  );
}

export async function fetchAgreementParty<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<AgreementParty, TAddress>> {
  const maybeAccount = await fetchMaybeAgreementParty(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeAgreementParty<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<AgreementParty, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeAgreementParty(maybeAccount);
}

export async function fetchAllAgreementParty(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<AgreementParty>[]> {
  const maybeAccounts = await fetchAllMaybeAgreementParty(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeAgreementParty(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<AgreementParty>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodeAgreementParty(maybeAccount),
  );
}

export function getAgreementPartySize(): number {
  return 91;
}
