/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const AGREEMENT_DISCRIMINATOR = new Uint8Array([
  83, 212, 5, 110, 225, 249, 197, 84,
]);

export function getAgreementDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(AGREEMENT_DISCRIMINATOR);
}

export type Agreement = {
  discriminator: ReadonlyUint8Array;
  agreementId: ReadonlyUint8Array;
  agreementType: number;
  status: number;
  visibility: number;
  proposer: Address;
  termsHash: ReadonlyUint8Array;
  termsUri: ReadonlyUint8Array;
  escrowVault: Address;
  escrowMint: Address;
  escrowTotal: bigint;
  numParties: number;
  numSigned: number;
  partiesAdded: number;
  createdAt: bigint;
  expiresAt: bigint;
  bump: number;
};

export type AgreementArgs = {
  agreementId: ReadonlyUint8Array;
  agreementType: number;
  status: number;
  visibility: number;
  proposer: Address;
  termsHash: ReadonlyUint8Array;
  termsUri: ReadonlyUint8Array;
  escrowVault: Address;
  escrowMint: Address;
  escrowTotal: number | bigint;
  numParties: number;
  numSigned: number;
  partiesAdded: number;
  createdAt: number | bigint;
  expiresAt: number | bigint;
  bump: number;
};

/** Gets the encoder for {@link AgreementArgs} account data. */
export function getAgreementEncoder(): FixedSizeEncoder<AgreementArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["agreementId", fixEncoderSize(getBytesEncoder(), 16)],
      ["agreementType", getU8Encoder()],
      ["status", getU8Encoder()],
      ["visibility", getU8Encoder()],
      ["proposer", getAddressEncoder()],
      ["termsHash", fixEncoderSize(getBytesEncoder(), 32)],
      ["termsUri", fixEncoderSize(getBytesEncoder(), 64)],
      ["escrowVault", getAddressEncoder()],
      ["escrowMint", getAddressEncoder()],
      ["escrowTotal", getU64Encoder()],
      ["numParties", getU8Encoder()],
      ["numSigned", getU8Encoder()],
      ["partiesAdded", getU8Encoder()],
      ["createdAt", getI64Encoder()],
      ["expiresAt", getI64Encoder()],
      ["bump", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: AGREEMENT_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link Agreement} account data. */
export function getAgreementDecoder(): FixedSizeDecoder<Agreement> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["agreementId", fixDecoderSize(getBytesDecoder(), 16)],
    ["agreementType", getU8Decoder()],
    ["status", getU8Decoder()],
    ["visibility", getU8Decoder()],
    ["proposer", getAddressDecoder()],
    ["termsHash", fixDecoderSize(getBytesDecoder(), 32)],
    ["termsUri", fixDecoderSize(getBytesDecoder(), 64)],
    ["escrowVault", getAddressDecoder()],
    ["escrowMint", getAddressDecoder()],
    ["escrowTotal", getU64Decoder()],
    ["numParties", getU8Decoder()],
    ["numSigned", getU8Decoder()],
    ["partiesAdded", getU8Decoder()],
    ["createdAt", getI64Decoder()],
    ["expiresAt", getI64Decoder()],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link Agreement} account data. */
export function getAgreementCodec(): FixedSizeCodec<AgreementArgs, Agreement> {
  return combineCodec(getAgreementEncoder(), getAgreementDecoder());
}

export function decodeAgreement<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<Agreement, TAddress>;
export function decodeAgreement<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<Agreement, TAddress>;
export function decodeAgreement<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<Agreement, TAddress> | MaybeAccount<Agreement, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getAgreementDecoder(),
  );
}

export async function fetchAgreement<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<Agreement, TAddress>> {
  const maybeAccount = await fetchMaybeAgreement(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeAgreement<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<Agreement, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeAgreement(maybeAccount);
}

export async function fetchAllAgreement(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<Agreement>[]> {
  const maybeAccounts = await fetchAllMaybeAgreement(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeAgreement(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<Agreement>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeAgreement(maybeAccount));
}

export function getAgreementSize(): number {
  return 247;
}
