/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from "@solana/kit";
import { AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS } from "../programs";

/** AgentKeyEqualsAuthority: Agent key must be different from authority */
export const AGENT_AGREEMENT_PROTOCOL_ERROR__AGENT_KEY_EQUALS_AUTHORITY = 0x1770; // 6000
/** ScopeExpired: Delegation scope has already expired */
export const AGENT_AGREEMENT_PROTOCOL_ERROR__SCOPE_EXPIRED = 0x1771; // 6001
/** Unauthorized: Unauthorized: signer is not the authority */
export const AGENT_AGREEMENT_PROTOCOL_ERROR__UNAUTHORIZED = 0x1772; // 6002
/** DelegationExpired: Agent delegation has expired */
export const AGENT_AGREEMENT_PROTOCOL_ERROR__DELEGATION_EXPIRED = 0x1773; // 6003
/** CannotSignAgreements: Agent does not have permission to sign agreements */
export const AGENT_AGREEMENT_PROTOCOL_ERROR__CANNOT_SIGN_AGREEMENTS = 0x1774; // 6004
/** CannotCommitFunds: Agent does not have permission to commit funds */
export const AGENT_AGREEMENT_PROTOCOL_ERROR__CANNOT_COMMIT_FUNDS = 0x1775; // 6005
/** EscrowExceedsLimit: Escrow amount exceeds delegation max_commit_lamports */
export const AGENT_AGREEMENT_PROTOCOL_ERROR__ESCROW_EXCEEDS_LIMIT = 0x1776; // 6006
/** SubAgentScopeExceedsParent: Sub-agent scope cannot exceed parent scope */
export const AGENT_AGREEMENT_PROTOCOL_ERROR__SUB_AGENT_SCOPE_EXCEEDS_PARENT = 0x1777; // 6007
/** MaxDelegationDepth: Maximum delegation depth is 2 levels (human -> agent -> sub-agent) */
export const AGENT_AGREEMENT_PROTOCOL_ERROR__MAX_DELEGATION_DEPTH = 0x1778; // 6008
/** InvalidAgreementType: Invalid agreement type */
export const AGENT_AGREEMENT_PROTOCOL_ERROR__INVALID_AGREEMENT_TYPE = 0x1779; // 6009
/** InvalidVisibility: Invalid visibility value */
export const AGENT_AGREEMENT_PROTOCOL_ERROR__INVALID_VISIBILITY = 0x177a; // 6010
/** InvalidRole: Invalid party role */
export const AGENT_AGREEMENT_PROTOCOL_ERROR__INVALID_ROLE = 0x177b; // 6011
/** InvalidPartyCount: Number of parties must be between 2 and 8 */
export const AGENT_AGREEMENT_PROTOCOL_ERROR__INVALID_PARTY_COUNT = 0x177c; // 6012
/** InvalidStatus: Agreement is not in the expected status */
export const AGENT_AGREEMENT_PROTOCOL_ERROR__INVALID_STATUS = 0x177d; // 6013
/** AgreementExpired: Agreement has expired */
export const AGENT_AGREEMENT_PROTOCOL_ERROR__AGREEMENT_EXPIRED = 0x177e; // 6014
/** AlreadySigned: Party has already signed */
export const AGENT_AGREEMENT_PROTOCOL_ERROR__ALREADY_SIGNED = 0x177f; // 6015
/** MaxPartiesExceeded: Maximum number of parties already added */
export const AGENT_AGREEMENT_PROTOCOL_ERROR__MAX_PARTIES_EXCEEDED = 0x1780; // 6016
/** EscrowDistributionMismatch: Escrow distribution does not sum to total */
export const AGENT_AGREEMENT_PROTOCOL_ERROR__ESCROW_DISTRIBUTION_MISMATCH = 0x1781; // 6017
/** EscrowNotDistributed: Escrow has not been fully distributed */
export const AGENT_AGREEMENT_PROTOCOL_ERROR__ESCROW_NOT_DISTRIBUTED = 0x1782; // 6018
/** AgentHasActiveAgreements: Agent has active agreements and cannot be revoked */
export const AGENT_AGREEMENT_PROTOCOL_ERROR__AGENT_HAS_ACTIVE_AGREEMENTS = 0x1783; // 6019

export type AgentAgreementProtocolError =
  | typeof AGENT_AGREEMENT_PROTOCOL_ERROR__AGENT_HAS_ACTIVE_AGREEMENTS
  | typeof AGENT_AGREEMENT_PROTOCOL_ERROR__AGENT_KEY_EQUALS_AUTHORITY
  | typeof AGENT_AGREEMENT_PROTOCOL_ERROR__AGREEMENT_EXPIRED
  | typeof AGENT_AGREEMENT_PROTOCOL_ERROR__ALREADY_SIGNED
  | typeof AGENT_AGREEMENT_PROTOCOL_ERROR__CANNOT_COMMIT_FUNDS
  | typeof AGENT_AGREEMENT_PROTOCOL_ERROR__CANNOT_SIGN_AGREEMENTS
  | typeof AGENT_AGREEMENT_PROTOCOL_ERROR__DELEGATION_EXPIRED
  | typeof AGENT_AGREEMENT_PROTOCOL_ERROR__ESCROW_DISTRIBUTION_MISMATCH
  | typeof AGENT_AGREEMENT_PROTOCOL_ERROR__ESCROW_EXCEEDS_LIMIT
  | typeof AGENT_AGREEMENT_PROTOCOL_ERROR__ESCROW_NOT_DISTRIBUTED
  | typeof AGENT_AGREEMENT_PROTOCOL_ERROR__INVALID_AGREEMENT_TYPE
  | typeof AGENT_AGREEMENT_PROTOCOL_ERROR__INVALID_PARTY_COUNT
  | typeof AGENT_AGREEMENT_PROTOCOL_ERROR__INVALID_ROLE
  | typeof AGENT_AGREEMENT_PROTOCOL_ERROR__INVALID_STATUS
  | typeof AGENT_AGREEMENT_PROTOCOL_ERROR__INVALID_VISIBILITY
  | typeof AGENT_AGREEMENT_PROTOCOL_ERROR__MAX_DELEGATION_DEPTH
  | typeof AGENT_AGREEMENT_PROTOCOL_ERROR__MAX_PARTIES_EXCEEDED
  | typeof AGENT_AGREEMENT_PROTOCOL_ERROR__SCOPE_EXPIRED
  | typeof AGENT_AGREEMENT_PROTOCOL_ERROR__SUB_AGENT_SCOPE_EXCEEDS_PARENT
  | typeof AGENT_AGREEMENT_PROTOCOL_ERROR__UNAUTHORIZED;

let agentAgreementProtocolErrorMessages:
  | Record<AgentAgreementProtocolError, string>
  | undefined;
if (process.env.NODE_ENV !== "production") {
  agentAgreementProtocolErrorMessages = {
    [AGENT_AGREEMENT_PROTOCOL_ERROR__AGENT_HAS_ACTIVE_AGREEMENTS]: `Agent has active agreements and cannot be revoked`,
    [AGENT_AGREEMENT_PROTOCOL_ERROR__AGENT_KEY_EQUALS_AUTHORITY]: `Agent key must be different from authority`,
    [AGENT_AGREEMENT_PROTOCOL_ERROR__AGREEMENT_EXPIRED]: `Agreement has expired`,
    [AGENT_AGREEMENT_PROTOCOL_ERROR__ALREADY_SIGNED]: `Party has already signed`,
    [AGENT_AGREEMENT_PROTOCOL_ERROR__CANNOT_COMMIT_FUNDS]: `Agent does not have permission to commit funds`,
    [AGENT_AGREEMENT_PROTOCOL_ERROR__CANNOT_SIGN_AGREEMENTS]: `Agent does not have permission to sign agreements`,
    [AGENT_AGREEMENT_PROTOCOL_ERROR__DELEGATION_EXPIRED]: `Agent delegation has expired`,
    [AGENT_AGREEMENT_PROTOCOL_ERROR__ESCROW_DISTRIBUTION_MISMATCH]: `Escrow distribution does not sum to total`,
    [AGENT_AGREEMENT_PROTOCOL_ERROR__ESCROW_EXCEEDS_LIMIT]: `Escrow amount exceeds delegation max_commit_lamports`,
    [AGENT_AGREEMENT_PROTOCOL_ERROR__ESCROW_NOT_DISTRIBUTED]: `Escrow has not been fully distributed`,
    [AGENT_AGREEMENT_PROTOCOL_ERROR__INVALID_AGREEMENT_TYPE]: `Invalid agreement type`,
    [AGENT_AGREEMENT_PROTOCOL_ERROR__INVALID_PARTY_COUNT]: `Number of parties must be between 2 and 8`,
    [AGENT_AGREEMENT_PROTOCOL_ERROR__INVALID_ROLE]: `Invalid party role`,
    [AGENT_AGREEMENT_PROTOCOL_ERROR__INVALID_STATUS]: `Agreement is not in the expected status`,
    [AGENT_AGREEMENT_PROTOCOL_ERROR__INVALID_VISIBILITY]: `Invalid visibility value`,
    [AGENT_AGREEMENT_PROTOCOL_ERROR__MAX_DELEGATION_DEPTH]: `Maximum delegation depth is 2 levels (human -> agent -> sub-agent)`,
    [AGENT_AGREEMENT_PROTOCOL_ERROR__MAX_PARTIES_EXCEEDED]: `Maximum number of parties already added`,
    [AGENT_AGREEMENT_PROTOCOL_ERROR__SCOPE_EXPIRED]: `Delegation scope has already expired`,
    [AGENT_AGREEMENT_PROTOCOL_ERROR__SUB_AGENT_SCOPE_EXCEEDS_PARENT]: `Sub-agent scope cannot exceed parent scope`,
    [AGENT_AGREEMENT_PROTOCOL_ERROR__UNAUTHORIZED]: `Unauthorized: signer is not the authority`,
  };
}

export function getAgentAgreementProtocolErrorMessage(
  code: AgentAgreementProtocolError,
): string {
  if (process.env.NODE_ENV !== "production") {
    return (
      agentAgreementProtocolErrorMessages as Record<
        AgentAgreementProtocolError,
        string
      >
    )[code];
  }

  return "Error message not available in production bundles.";
}

export function isAgentAgreementProtocolError<
  TProgramErrorCode extends AgentAgreementProtocolError,
>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode,
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    AGENT_AGREEMENT_PROTOCOL_PROGRAM_ADDRESS,
    code,
  );
}
